### ISSUE TITLE
Segfault with libcapstone4

### ISSUE THREAD

**Issue by vient** [nyx-fuzz/libxdc_experiments#3]
Hi! I want to test libxdc but instructions are unclear. As I learned from `make.sh` error, I need libcapstone4 installed so I downloaded sources, compiled and installed the `v4` branch. After that all tests in test_data/dynamic_test.sh are segfaulted on NULL ptr deref on line https://github.com/nyx-fuzz/libxdc/blob/31347a852b07159d196ebf6ce0a58624aad8811e/src/disassembler.c#L260 - ins is 0. I've also tried to compile 4.0.2 release with same result. What version of libcapstone is supposed to be used?

**Comment by vient** [comment]
Oh well, this issue should be in libxdc repo.

**Comment by eqv** [comment]
Dammit I could have sworn that we fixed a version somewhere. But since I can't find it it seems we naively didn't. Afaik what you did sounds 100% right. I will need to investigate.

**Comment by eqv** [comment]
We have been using 4.0.1 (f9c6a90489be7b3637ff1c7298e45efafe7cf1b9) does that work for you?

**Comment by vient** [comment]
I've downloaded [4.0.1 sources](https://github.com/aquynh/capstone/releases/tag/4.0.1), compiled them by running `./make.sh` and symlinked `/lib/libcapstone.so.4` to compiled library. Result is the same, NULL deref on that line.

Just in case, I'm using following gdb command line in test_data folder (derived from the first line of dynamic_test.sh)
`ASAN_OPTIONS=detect_leaks=1 LD_LIBRARY_PATH=../bin/ gdb -q --args ../bin/tester 0x400000 0x427000  ./Unzip/data ./Unzip/trace 0x15b89190dfa291b2 simple`

**Comment by eqv** [comment]
this might seem like a stupid question, but having had that issue a few times myself: have you used ldd / lddtree to verify that the correct library was also linked?

**Comment by vient** [comment]
Yes, I checked it both by using ldd and checking vmmap in gdb. After my previous comment I thought that I might have compiled with v3 headers so I unistalled capstone packages, installed 4.0.1, no luck.

Maybe you may describe how you compile libxdc and I'll try to replicate it in a docker/vm?

**Comment by schumilo** [comment]
Sure! Here you go! 
I can confirm that it works like a charm with this Dockerfile.

Copy the following content into `./Dockerfile`:
```
FROM ubuntu:18.04

RUN apt-get -y update && \
    apt-get -y install sudo \ 
    apt-utils \
    build-essential \
    openssl \
    clang \
    git \
    vim 

git clone https://github.com/aquynh/capstone.git && \
    cd capstone && \
    git checkout v4 && \
    make && \
    make install && \
    cd - && \
    git clone https://github.com/nyx-fuzz/libxdc.git && \
    cd libxdc && \
    make && \
    make install && \
    cd - && \
    git clone https://github.com/nyx-fuzz/libxdc_experiments.git && \
    cd libxdc_experiments/ && \
    cp -R ../libxdc/build/ bin/ && \
    cd test_data && \
    sh dynamic_test.sh && \
    sh performance.sh && 
    echo "All tests passed successfully"
```

And then simply run: 

```
docker build . -t libxdc
# docker image rm libxdc
```

**Comment by vient** [comment]
I finally got time to test it and it seems that you delete test_data scripts just half an hour ago. Are there any other scripts which I can test with or I can restore old ones (use old revision)?

Edit: looks like run_regression_tests.sh in root folder is what I want.

**Comment by vient** [comment]
There is no segfault in docker, thanks (but one test is failing with "decoder_page_fault" and another with "Page not found: 0x7ffff7fcf000! Aborting!", don't know if it is expected or not).

**Comment by schumilo** [comment]
Yeah, it's an expected error for one specific test case (`test_data/dyn_test`) where we test if the decoder is able to handle missing or swapped-out pages. So, nothing to worry about :)
